version: '3'

networks:
  my_network:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx_laravel_base
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mariadb
    networks:
      - my_network
  mariadb:
    image: mariadb:10.6.4
    container_name: mariadb_laravel_base
    restart: unless-stopped
    tty: true
    ports:
      - "33060:3306"
    volumes:
      - ./docker/mariadb/my.cnf:/etc/mysql/my.cnf
    environment:
      MYSQL_DATABASE: laravel_base
      MYSQL_USER: caerux
      MYSQL_PASSWORD: .caerux
      MYSQL_ROOT_PASSWORD: .caerux
      SERVICE_NAME: mysql
    networks:
      - my_network
  php:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: php_laravel_base
    volumes:
      - ./:/var/www/html
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    ports:
      - "9090:9000"
    networks:
      - my_network
